### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#28]
currently we don't have a license on this, not sure which one to pick. this is probably urgent.

**Comment by pufferfish101007** [comment]
At the moment package.json says ISC, I'd recommend GNU or some variant as it basically means that people can't troll us, make money out of this or make any closed-source applications out of it.

**Comment by jeffalo** [comment]
> can't troll us, make money out of this or make any closed-source applications out of it.

one issue i forsee with that is if this becomes big, then we cannot make money from it due to code being contributed back in. so a license which allows commercial use might be better.

**Comment by pufferfish101007** [comment]
> > can't troll us, make money out of this or make any closed-source applications out of it.
> 
> one issue i forsee with that is if this becomes big, then we cannot make money from it due to code being contributed back in. so a license which allows commercial use might be better.

Woops sorry it *does* allow commercial use, but it just has to be ipen source. Sorry I got confused there. It turns out that there are basically no licenses that stop people from using things commercially, and the ones that do stop it are very vague and you need to sign a bunch of agreements to contribute.
 I've taken a look through choosealicense.com and in my opinion the best course of action is the GNU General Public License v3.0;  that's just my opinion - I think GNU is the best and out of the available GNU licenses, GPL v3 seems most suited for our causes. Anyway, merry Christmas!

**Comment by jeffalo** [comment]
merry christmas to you too! @GrahamSH-LLK what do you think?

**Comment by pufferfish101007** [comment]
@jeffalo pls close :)

**Comment by jeffalo** [comment]
resolved in #45
