### ISSUE TITLE
rate limit

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#34]

**Comment by jeffalo** [comment]
what should those rate limits be?

**Comment by GrahamSH-LLK** [comment]
- Create account: 5 per hour?
- Pages: 250 per hour?
- API: 100 per hour?

**Comment by pufferfish101007** [comment]
> * Create account: 5 per hour?

That seems reasonable.
> * Pages: 250 per hour?

That's only one page every 15 seconds... mind you, chances are people aren't going to be on for an hour at a time. But maybe 500/hr is better?
> * API: 100 per hour?

I think for the api it would be better to do it in a time frame shorter than an hour, otherwise someone could fire off a bazillion requests really quickly and crash the servers. And I think it should be a bit higher, depending on how good Jeffalo's servers are. I think it might be better to have it as 60 requests every 15 minutes?

Either way, I can do this. I'll keep the limits as suggested by GrahamSH.

**Comment by jeffalo** [comment]
perhaps pages should not be rate limited at all?

**Comment by pufferfish101007** [comment]
> perhaps pages should not be rate limited at all?

That actually makes a lot of sense :)
